### ISSUE TITLE
riot-mui and riot not matching on jspm

### ISSUE THREAD

**Issue by rolldone** [kysonic/riot-mui#49]
can you explain to me how to define riot-mui on jspm, it still like not matching with my riot module, the error see  at below : 
`system.src.js:123 Uncaught (in promise) Error: (SystemJS) riot is not defined
	ReferenceError: riot is not defined
	    at Object.riot.tag2.e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:1658)
	    at e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:101)
	    at Object.eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:23236)
	    at e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:101)
	    at Object.defineProperty.value (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:477)
	    at Object.eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:487)
	    at eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:3:4)
	    at eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:4:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js
	Evaluating http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0.js
	Error loading http://localhost:8080/src/index.js
	    at Object.riot.tag2.e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:1658)
	    at e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:101)
	    at Object.eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:23236)
	    at e (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:101)
	    at Object.defineProperty.value (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:477)
	    at Object.eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:2:487)
	    at eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:3:4)
	    at eval (http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js:4:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0/build/js/riot-mui-min.js
	Evaluating http://localhost:8080/jspm_packages/npm/riot-mui@0.1.0.js
	Error loading http://localhost:8080/src/index.js`

**Comment by kysonic** [comment]
I'm not sure that it's related with riot-mui therefore you should go to [riot#2084](https://github.com/riot/riot/issues/2084) to solve this problem.
